/*
 * MIT License
 *
 * Copyright (c) 2022 Ursin Filli
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package dev.ursinn.velocity.nici.management;

import com.velocitypowered.api.proxy.Player;
import com.velocitypowered.api.proxy.ProxyServer;
import com.velocitypowered.api.proxy.ServerConnection;
import com.velocitypowered.api.proxy.server.RegisteredServer;
import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.format.NamedTextColor;
import org.jetbrains.annotations.NotNull;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

public class Utils {

    private Utils() {
        throw new IllegalStateException("Utility class");
    }

    public static @NotNull Component getServerName(String serverName) {
        return Component.text(Character.toUpperCase(serverName.charAt(0)) + serverName.substring(1).replace("_", "."));
    }

    public static @NotNull Component getServerName(Optional<ServerConnection> serverConnection) {
        return serverConnection
                .map(connection -> getServerName(connection.getServerInfo().getName()))
                .orElse(Component.text("UNKNOWN"));
    }

    public static @NotNull Component getPrefix(Player player) {
        if (player.hasPermission("nici.management.admin")) {
            return Component.text()
                    .content("[Admin] ").color(NamedTextColor.RED)
                    .append(Component.text(player.getUsername()).color(NamedTextColor.GOLD))
                    .build();
        }

        return Component.text(player.getUsername()).color(NamedTextColor.GREEN);
    }

    public static void broadcast(ProxyServer proxyServer, Player player, Component message) {
        Optional<ServerConnection> serverConnection = player.getCurrentServer();
        RegisteredServer registeredServer = null;
        if (serverConnection.isPresent()) {
            registeredServer = serverConnection.get().getServer();
        }

        Component component = Component.text()
                .content("")
                .append(Component.text("[").color(NamedTextColor.GRAY))
                .append(Utils.getServerName(serverConnection).color(NamedTextColor.YELLOW))
                .append(Component.text("] ").color(NamedTextColor.GRAY))
                .append(Utils.getPrefix(player))
                .append(Component.text(":"))
                .append(Component.space())
                .append(message)
                .build();

        // send message to other server
        for (RegisteredServer server : proxyServer.getAllServers()) {
            if (!Objects.equals(server, registeredServer)) {
                server.sendMessage(component);
            }
        }
    }

    public static List<String> getBadWordsList() {
        List<String> wordlist = new ArrayList<>();
        wordlist.add("1488");
        wordlist.add("8=D");
        wordlist.add("A55hole");
        wordlist.add("abortion");
        wordlist.add("ahole");
        wordlist.add("AIDs");
        wordlist.add("ainujin");
        wordlist.add("ainuzin");
        wordlist.add("akimekura");
        wordlist.add("Anal");
        wordlist.add("anus");
        wordlist.add("anuses");
        wordlist.add("Anushead");
        wordlist.add("anuslick");
        wordlist.add("anuss");
        wordlist.add("aokan");
        wordlist.add("Arsch");
        wordlist.add("Arschloch");
        wordlist.add("arse");
        wordlist.add("arsed");
        wordlist.add("arsehole");
        wordlist.add("arseholed");
        wordlist.add("arseholes");
        wordlist.add("arseholing");
        wordlist.add("arselicker");
        wordlist.add("arses");
        wordlist.add("Ass");
        wordlist.add("asshat");
        wordlist.add("asshole");
        wordlist.add("Auschwitz");
        wordlist.add("b00bz");
        wordlist.add("b1tc");
        wordlist.add("Baise");
        wordlist.add("bakachon");
        wordlist.add("bakatyon");
        wordlist.add("Ballsack");
        wordlist.add("BAMF");
        wordlist.add("Bastard");
        wordlist.add("Beaner");
        wordlist.add("Beeatch");
        wordlist.add("beeeyotch");
        wordlist.add("beefwhistle");
        wordlist.add("beeotch");
        wordlist.add("Beetch");
        wordlist.add("beeyotch");
        wordlist.add("Bellend");
        wordlist.add("bestiality");
        wordlist.add("beyitch");
        wordlist.add("beyotch");
        wordlist.add("Biach");
        wordlist.add("bin laden");
        wordlist.add("binladen");
        wordlist.add("biotch");
        wordlist.add("bitch");
        wordlist.add("Bitching");
        wordlist.add("blad");
        wordlist.add("bladt");
        wordlist.add("blowjob");
        wordlist.add("blowme");
        wordlist.add("blyad");
        wordlist.add("blyadt");
        wordlist.add("bon3r");
        wordlist.add("boner");
        wordlist.add("boobs");
        wordlist.add("Btch");
        wordlist.add("Bukakke");
        wordlist.add("Bullshit");
        wordlist.add("bung");
        wordlist.add("butagorosi");
        wordlist.add("butthead");
        wordlist.add("Butthole");
        wordlist.add("Buttplug");
        wordlist.add("c0ck");
        wordlist.add("Cabron");
        wordlist.add("Cacca");
        wordlist.add("Cadela");
        wordlist.add("Cagada");
        wordlist.add("Cameljockey");
        wordlist.add("Caralho");
        wordlist.add("castrate");
        wordlist.add("Cazzo");
        wordlist.add("ceemen");
        wordlist.add("ch1nk");
        wordlist.add("chankoro");
        wordlist.add("chieokure");
        wordlist.add("chikusatsu");
        wordlist.add("Ching chong");
        wordlist.add("Chinga");
        wordlist.add("Chingada Madre");
        wordlist.add("Chingado");
        wordlist.add("Chingate");
        wordlist.add("chink");
        wordlist.add("chinpo");
        wordlist.add("Chlamydia");
        wordlist.add("choad");
        wordlist.add("chode");
        wordlist.add("chonga");
        wordlist.add("chonko");
        wordlist.add("chonkoro");
        wordlist.add("chourimbo");
        wordlist.add("chourinbo");
        wordlist.add("chourippo");
        wordlist.add("chuurembo");
        wordlist.add("chuurenbo");
        wordlist.add("circlejerk");
        wordlist.add("cl1t");
        wordlist.add("cli7");
        wordlist.add("clit");
        wordlist.add("clitoris");
        wordlist.add("cocain");
        wordlist.add("Cocaine");
        wordlist.add("cock");
        wordlist.add("Cocksucker");
        wordlist.add("Coglione");
        wordlist.add("Coglioni");
        wordlist.add("coitus");
        wordlist.add("coituss");
        wordlist.add("cojelon");
        wordlist.add("cojones");
        wordlist.add("condom");
        wordlist.add("coon");
        wordlist.add("coon hunt");
        wordlist.add("coon kill");
        wordlist.add("coonhunt");
        wordlist.add("coonkill");
        wordlist.add("Cooter");
        wordlist.add("cotton pic");
        wordlist.add("cotton pik");
        wordlist.add("cottonpic");
        wordlist.add("cottonpik");
        wordlist.add("Crackhead");
        wordlist.add("CSAM");
        wordlist.add("Culear");
        wordlist.add("Culero");
        wordlist.add("Culo");
        wordlist.add("Cum");
        wordlist.add("cun7");
        wordlist.add("cunt");
        wordlist.add("cvn7");
        wordlist.add("cvnt");
        wordlist.add("cyka");
        wordlist.add("d1kc");
        wordlist.add("d4go");
        wordlist.add("dago");
        wordlist.add("Darkie");
        wordlist.add("Darkie");
        wordlist.add("Deez Nuts");
        wordlist.add("deeznut");
        wordlist.add("deeznuts");
        wordlist.add("Dickhead");
        wordlist.add("dikc");
        wordlist.add("dildo");
        wordlist.add("Dio Bestia");
        wordlist.add("dong");
        wordlist.add("dongs");
        wordlist.add("douche");
        wordlist.add("Downie");
        wordlist.add("Downy");
        wordlist.add("Dumbass");
        wordlist.add("Durka durka");
        wordlist.add("Dyke");
        wordlist.add("Ejaculate");
        wordlist.add("Encule");
        wordlist.add("enjokousai");
        wordlist.add("enzyokousai");
        wordlist.add("etahinin");
        wordlist.add("etambo");
        wordlist.add("etanbo");
        wordlist.add("f0ck");
        wordlist.add("f0kc");
        wordlist.add("f3lch");
        wordlist.add("facking");
        wordlist.add("fag");
        wordlist.add("faggot");
        wordlist.add("Fanculo");
        wordlist.add("Fanny");
        wordlist.add("fatass");
        wordlist.add("fck");
        wordlist.add("Fckn");
        wordlist.add("fcuk");
        wordlist.add("fcuuk");
        wordlist.add("felch");
        wordlist.add("Fetish");
        wordlist.add("Fgt");
        wordlist.add("FiCKDiCH");
        wordlist.add("Figlio di Puttana");
        wordlist.add("fku");
        wordlist.add("fock");
        wordlist.add("fokc");
        wordlist.add("foreskin");
        wordlist.add("Fotze");
        wordlist.add("Foutre");
        wordlist.add("fucc");
        wordlist.add("fuck");
        wordlist.add("Fucking");
        wordlist.add("fuct");
        wordlist.add("fujinoyamai");
        wordlist.add("fukashokumin");
        wordlist.add("Fupa");
        wordlist.add("fuuck");
        wordlist.add("fuuuck");
        wordlist.add("fuuuuck");
        wordlist.add("fuuuuuck");
        wordlist.add("fuuuuuuck");
        wordlist.add("fuuuuuuuck");
        wordlist.add("fuuuuuuuuck");
        wordlist.add("fuuuuuuuuuck");
        wordlist.add("fuuuuuuuuuu");
        wordlist.add("fvck");
        wordlist.add("fxck");
        wordlist.add("fxuxcxk");
        wordlist.add("g000k");
        wordlist.add("g00k");
        wordlist.add("g0ok");
        wordlist.add("gestapo");
        wordlist.add("go0k");
        wordlist.add("god damn");
        wordlist.add("goldenshowers");
        wordlist.add("golliwogg");
        wordlist.add("gollywog");
        wordlist.add("Gooch");
        wordlist.add("gook");
        wordlist.add("goook");
        wordlist.add("Gyp");
        wordlist.add("h0m0");
        wordlist.add("h0mo");
        wordlist.add("h1tl3");
        wordlist.add("h1tle");
        wordlist.add("hairpie");
        wordlist.add("hakujakusha");
        wordlist.add("hakuroubyo");
        wordlist.add("hakuzyakusya");
        wordlist.add("hantoujin");
        wordlist.add("hantouzin");
        wordlist.add("Herpes");
        wordlist.add("hitl3r");
        wordlist.add("hitler");
        wordlist.add("hitlr");
        wordlist.add("holocaust");
        wordlist.add("hom0");
        wordlist.add("homo");
        wordlist.add("honky");
        wordlist.add("Hooker");
        wordlist.add("hor3");
        wordlist.add("hukasyokumin");
        wordlist.add("Hure");
        wordlist.add("Hurensohn");
        wordlist.add("huzinoyamai");
        wordlist.add("hymen");
        wordlist.add("inc3st");
        wordlist.add("incest");
        wordlist.add("Inculato");
        wordlist.add("Injun");
        wordlist.add("intercourse");
        wordlist.add("inugoroshi");
        wordlist.add("inugorosi");
        wordlist.add("j1g4b0");
        wordlist.add("j1g4bo");
        wordlist.add("j1gab0");
        wordlist.add("j1gabo");
        wordlist.add("Jack Off");
        wordlist.add("jackass");
        wordlist.add("jap");
        wordlist.add("JerkOff");
        wordlist.add("jig4b0");
        wordlist.add("jig4bo");
        wordlist.add("jigabo");
        wordlist.add("Jigaboo");
        wordlist.add("jiggaboo");
        wordlist.add("jizz");
        wordlist.add("Joder");
        wordlist.add("Joto");
        wordlist.add("Jungle Bunny");
        wordlist.add("junglebunny");
        wordlist.add("k k k");
        wordlist.add("k1k3");
        wordlist.add("kichigai");
        wordlist.add("kik3");
        wordlist.add("Kike");
        wordlist.add("kikeiji");
        wordlist.add("kikeizi");
        wordlist.add("Kilurself");
        wordlist.add("kitigai");
        wordlist.add("kkk");
        wordlist.add("klu klux");
        wordlist.add("Klu Klux Klan");
        wordlist.add("kluklux");
        wordlist.add("knobhead");
        wordlist.add("koon hunt");
        wordlist.add("koon kill");
        wordlist.add("koonhunt");
        wordlist.add("koonkill");
        wordlist.add("koroshiteyaru");
        wordlist.add("koumoujin");
        wordlist.add("koumouzin");
        wordlist.add("ku klux klan");
        wordlist.add("kun7");
        wordlist.add("kurombo");
        wordlist.add("Kurva");
        wordlist.add("Kurwa");
        wordlist.add("kxkxk");
        wordlist.add("l3sb0");
        wordlist.add("lezbo");
        wordlist.add("lezzie");
        wordlist.add("m07th3rfukr");
        wordlist.add("m0th3rfvk3r");
        wordlist.add("m0th3rfvker");
        wordlist.add("Madonna Puttana");
        wordlist.add("manberries");
        wordlist.add("manko");
        wordlist.add("manshaft");
        wordlist.add("Maricon");
        wordlist.add("Masterbat");
        wordlist.add("masterbate");
        wordlist.add("Masturbacion");
        wordlist.add("masturbait");
        wordlist.add("Masturbare");
        wordlist.add("Masturbate");
        wordlist.add("Masturbazione");
        wordlist.add("Merda");
        wordlist.add("Merde");
        wordlist.add("Meth");
        wordlist.add("Mierda");
        wordlist.add("milf");
        wordlist.add("Minge");
        wordlist.add("Miststück");
        wordlist.add("mitsukuchi");
        wordlist.add("mitukuti");
        wordlist.add("Molest");
        wordlist.add("molester");
        wordlist.add("molestor");
        wordlist.add("Mong");
        wordlist.add("Moon Cricket");
        wordlist.add("moth3rfucer");
        wordlist.add("moth3rfvk3r");
        wordlist.add("moth3rfvker");
        wordlist.add("motherfucker");
        wordlist.add("Mulatto");
        wordlist.add("n1663r");
        wordlist.add("n1664");
        wordlist.add("n166a");
        wordlist.add("n166er");
        wordlist.add("n1g3r");
        wordlist.add("n1German");
        wordlist.add("n1gg3r");
        wordlist.add("n1gGerman");
        wordlist.add("n3gro");
        wordlist.add("n4g3r");
        wordlist.add("n4gg3r");
        wordlist.add("n4gGerman");
        wordlist.add("n4z1");
        wordlist.add("nag3r");
        wordlist.add("nagg3r");
        wordlist.add("nagGerman");
        wordlist.add("natzi");
        wordlist.add("naz1");
        wordlist.add("nazi");
        wordlist.add("nazl");
        wordlist.add("neGerman");
        wordlist.add("ngGerman");
        wordlist.add("nggr");
        wordlist.add("NhigGerman");
        wordlist.add("ni666");
        wordlist.add("ni66a");
        wordlist.add("ni66er");
        wordlist.add("ni66g");
        wordlist.add("ni6g");
        wordlist.add("ni6g6");
        wordlist.add("ni6gg");
        wordlist.add("Nig");
        wordlist.add("nig66");
        wordlist.add("nig6g");
        wordlist.add("nigar");
        wordlist.add("niGerman");
        wordlist.add("nigg3");
        wordlist.add("nigg6");
        wordlist.add("nigga");
        wordlist.add("niggaz");
        wordlist.add("nigGerman");
        wordlist.add("nigglet");
        wordlist.add("niggr");
        wordlist.add("nigguh");
        wordlist.add("niggur");
        wordlist.add("niggy");
        wordlist.add("niglet");
        wordlist.add("Nignog");
        wordlist.add("nimpinin");
        wordlist.add("ninpinin");
        wordlist.add("Nipples");
        wordlist.add("niqqa");
        wordlist.add("niqqer");
        wordlist.add("Nonce");
        wordlist.add("nugga");
        wordlist.add("Nutsack");
        wordlist.add("Nutted");
        wordlist.add("nygGerman");
        wordlist.add("omeko");
        wordlist.add("Orgy");
        wordlist.add("p3n15");
        wordlist.add("p3n1s");
        wordlist.add("p3ni5");
        wordlist.add("p3nis");
        wordlist.add("p3nl5");
        wordlist.add("p3nls");
        wordlist.add("Paki");
        wordlist.add("Panties");
        wordlist.add("Pedo");
        wordlist.add("pedoph");
        wordlist.add("pedophile");
        wordlist.add("pen15");
        wordlist.add("pen1s");
        wordlist.add("Pendejo");
        wordlist.add("peni5");
        wordlist.add("penile");
        wordlist.add("penis");
        wordlist.add("Penis");
        wordlist.add("penl5");
        wordlist.add("penls");
        wordlist.add("penus");
        wordlist.add("Perra");
        wordlist.add("phaggot");
        wordlist.add("phagot");
        wordlist.add("phuck");
        wordlist.add("Pikey");
        wordlist.add("Pinche");
        wordlist.add("Pizda");
        wordlist.add("Polla");
        wordlist.add("Porca Madonna");
        wordlist.add("Porch monkey");
        wordlist.add("Porn");
        wordlist.add("Porra");
        wordlist.add("pr1ck");
        wordlist.add("preteen");
        wordlist.add("prick");
        wordlist.add("pu555y");
        wordlist.add("pu55y");
        wordlist.add("pub1c");
        wordlist.add("Pube");
        wordlist.add("pubic");
        wordlist.add("pun4ni");
        wordlist.add("pun4nl");
        wordlist.add("Punal");
        wordlist.add("punan1");
        wordlist.add("punani");
        wordlist.add("punanl");
        wordlist.add("puss1");
        wordlist.add("puss3");
        wordlist.add("puss5");
        wordlist.add("pusse");
        wordlist.add("pussi");
        wordlist.add("Pussies");
        wordlist.add("pusss1");
        wordlist.add("pussse");
        wordlist.add("pusssi");
        wordlist.add("pusssl");
        wordlist.add("pusssy");
        wordlist.add("Pussy");
        wordlist.add("Puta");
        wordlist.add("Putain");
        wordlist.add("Pute");
        wordlist.add("Puto");
        wordlist.add("Puttana");
        wordlist.add("Puttane");
        wordlist.add("Puttaniere");
        wordlist.add("puzzy");
        wordlist.add("pvssy");
        wordlist.add("queef");
        wordlist.add("r3c7um");
        wordlist.add("r4p15t");
        wordlist.add("r4p1st");
        wordlist.add("r4p3");
        wordlist.add("r4pi5t");
        wordlist.add("r4pist");
        wordlist.add("raape");
        wordlist.add("raghead");
        wordlist.add("raibyo");
        wordlist.add("Raip");
        wordlist.add("rap15t");
        wordlist.add("rap1st");
        wordlist.add("Rapage");
        wordlist.add("rape");
        wordlist.add("Raped");
        wordlist.add("rapi5t");
        wordlist.add("Raping");
        wordlist.add("rapist");
        wordlist.add("rectum");
        wordlist.add("Red Tube");
        wordlist.add("Reggin");
        wordlist.add("reipu");
        wordlist.add("retard");
        wordlist.add("Ricchione");
        wordlist.add("rimjob");
        wordlist.add("rizzape");
        wordlist.add("rompari");
        wordlist.add("Salaud");
        wordlist.add("Salope");
        wordlist.add("sangokujin");
        wordlist.add("sangokuzin");
        wordlist.add("santorum");
        wordlist.add("Scheiße");
        wordlist.add("Schlampe");
        wordlist.add("Schlampe");
        wordlist.add("schlong");
        wordlist.add("Schwuchtel");
        wordlist.add("Scrote");
        wordlist.add("secks");
        wordlist.add("seishinhakujaku");
        wordlist.add("seishinijo");
        wordlist.add("seisinhakuzyaku");
        wordlist.add("seisinizyo");
        wordlist.add("Semen");
        wordlist.add("semushiotoko");
        wordlist.add("semusiotoko");
        wordlist.add("sh|t");
        wordlist.add("sh17");
        wordlist.add("sh1t");
        wordlist.add("Shemae");
        wordlist.add("Shat");
        wordlist.add("shi7");
        wordlist.add("shinajin");
        wordlist.add("shinheimin");
        wordlist.add("shirakko");
        wordlist.add("shit");
        wordlist.add("Shitty");
        wordlist.add("shl7");
        wordlist.add("shlt");
        wordlist.add("shokubutsuningen");
        wordlist.add("sinazin");
        wordlist.add("sinheimin");
        wordlist.add("Skank");
        wordlist.add("SMD");
        wordlist.add("Sodom");
        wordlist.add("sofa king");
        wordlist.add("sofaking");
        wordlist.add("Spanishick");
        wordlist.add("Spanishook");
        wordlist.add("Spanishunk");
        wordlist.add("STD");
        wordlist.add("STDs");
        wordlist.add("Succhia Cazzi");
        wordlist.add("suck my");
        wordlist.add("suckmy");
        wordlist.add("syokubutuningen");
        wordlist.add("Taint");
        wordlist.add("Tapatte");
        wordlist.add("Tapette");
        wordlist.add("Tarlouse");
        wordlist.add("tea bag");
        wordlist.add("teabag");
        wordlist.add("teebag");
        wordlist.add("teensex");
        wordlist.add("teino");
        wordlist.add("Testa di Cazzo");
        wordlist.add("Testicles");
        wordlist.add("Thot");
        wordlist.add("tieokure");
        wordlist.add("tinpo");
        wordlist.add("Tits");
        wordlist.add("tokushugakkyu");
        wordlist.add("tokusyugakkyu");
        wordlist.add("torukoburo");
        wordlist.add("torukojo");
        wordlist.add("torukozyo");
        wordlist.add("tosatsu");
        wordlist.add("tosatu");
        wordlist.add("towelhead");
        wordlist.add("Tranny");
        wordlist.add("tunbo");
        wordlist.add("tw47");
        wordlist.add("tw4t");
        wordlist.add("twat");
        wordlist.add("tyankoro");
        wordlist.add("tyonga");
        wordlist.add("tyonko");
        wordlist.add("tyonkoro");
        wordlist.add("tyourinbo");
        wordlist.add("tyourippo");
        wordlist.add("tyurenbo");
        wordlist.add("ushigoroshi");
        wordlist.add("usigorosi");
        wordlist.add("v461n4");
        wordlist.add("v461na");
        wordlist.add("v46in4");
        wordlist.add("v46ina");
        wordlist.add("v4g1n4");
        wordlist.add("v4g1na");
        wordlist.add("v4gin4");
        wordlist.add("v4gina");
        wordlist.add("va61n4");
        wordlist.add("va61na");
        wordlist.add("va6in4");
        wordlist.add("va6ina");
        wordlist.add("Vaccagare");
        wordlist.add("Vaffanculo");
        wordlist.add("Vag");
        wordlist.add("vag1n4");
        wordlist.add("vag1na");
        wordlist.add("vagin4");
        wordlist.add("vagina");
        wordlist.add("VateFaire");
        wordlist.add("vvhitepower");
        wordlist.add("w3tb4ck");
        wordlist.add("w3tback");
        wordlist.add("Wank");
        wordlist.add("wanker");
        wordlist.add("wetb4ck");
        wordlist.add("wetback");
        wordlist.add("wh0r3");
        wordlist.add("wh0re");
        wordlist.add("white power");
        wordlist.add("whitepower");
        wordlist.add("whor3");
        wordlist.add("whore");
        wordlist.add("Wog");
        wordlist.add("Wop");
        wordlist.add("x8lp3t");
        wordlist.add("xbl pet");
        wordlist.add("XBLPET");
        wordlist.add("XBLRewards");
        wordlist.add("Xl3LPET");
        wordlist.add("yabunirami");
        wordlist.add("Zipperhead");
        wordlist.add("Блядь");
        wordlist.add("сука");
        wordlist.add("アオカン");
        wordlist.add("あおかん");
        wordlist.add("イヌゴロシ");
        wordlist.add("いぬごろし");
        wordlist.add("インバイ");
        wordlist.add("いんばい");
        wordlist.add("オナニー");
        wordlist.add("オナニー");
        wordlist.add("オメコ");
        wordlist.add("カワラコジキ");
        wordlist.add("かわらこじき");
        wordlist.add("かわらこじき");
        wordlist.add("かわらもの");
        wordlist.add("キケイジ");
        wordlist.add("きけいじ");
        wordlist.add("キチガイ");
        wordlist.add("きちがい");
        wordlist.add("キンタマ");
        wordlist.add("きんたま");
        wordlist.add("クロンボ");
        wordlist.add("くろんぼ");
        wordlist.add("コロシテヤル");
        wordlist.add("ころしてやる");
        wordlist.add("シナジン");
        wordlist.add("しなじん");
        wordlist.add("タチンボ");
        wordlist.add("たちんぼ");
        wordlist.add("チョンコウ");
        wordlist.add("ちょんこう");
        wordlist.add("ちょんこう");
        wordlist.add("チョンコロ");
        wordlist.add("ちょんころ");
        wordlist.add("ちょん公");
        wordlist.add("チンポ");
        wordlist.add("ちんぽ");
        wordlist.add("ツンボ");
        wordlist.add("つんぼ");
        wordlist.add("とるこじょう");
        wordlist.add("とるこぶろ");
        wordlist.add("トルコ嬢");
        wordlist.add("トルコ風呂");
        wordlist.add("ニガー");
        wordlist.add("ニグロ");
        wordlist.add("にんぴにん");
        wordlist.add("はんとうじん");
        wordlist.add("マンコ");
        wordlist.add("まんこ");
        wordlist.add("レイプ");
        wordlist.add("れいぷ");
        wordlist.add("低能");
        wordlist.add("屠殺");
        wordlist.add("強姦");
        wordlist.add("援交");
        wordlist.add("支那人");
        wordlist.add("精薄");
        wordlist.add("精薄者");
        wordlist.add("輪姦");
        return wordlist;
    }

}
