/*
 * MIT License
 *
 * Copyright (c) 2022 Ursin Filli
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package dev.ursinn.velocity.nici.management.modules;

import com.velocitypowered.api.event.PostOrder;
import com.velocitypowered.api.event.Subscribe;
import com.velocitypowered.api.event.player.PlayerChatEvent;
import com.velocitypowered.api.proxy.Player;
import com.velocitypowered.api.proxy.ProxyServer;
import com.velocitypowered.api.proxy.ServerConnection;
import com.velocitypowered.api.proxy.server.RegisteredServer;
import dev.ursinn.velocity.nici.management.Utils;
import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.TextComponent;
import net.kyori.adventure.text.format.NamedTextColor;
import org.slf4j.Logger;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

public class Message {

    private final ProxyServer proxyServer;
    private final List<String> wordList;

    public Message(ProxyServer proxyServer, Logger logger) {
        this.proxyServer = proxyServer;
        this.wordList = new ArrayList<>();

        initWordList();
        logger.info("Loaded Message Module.");
    }

    private void initWordList() {
        this.wordList.add("1488");
        this.wordList.add("8=D");
        this.wordList.add("A55hole");
        this.wordList.add("abortion");
        this.wordList.add("ahole");
        this.wordList.add("AIDs");
        this.wordList.add("ainujin");
        this.wordList.add("ainuzin");
        this.wordList.add("akimekura");
        this.wordList.add("Anal");
        this.wordList.add("anus");
        this.wordList.add("anuses");
        this.wordList.add("Anushead");
        this.wordList.add("anuslick");
        this.wordList.add("anuss");
        this.wordList.add("aokan");
        this.wordList.add("Arsch");
        this.wordList.add("Arschloch");
        this.wordList.add("arse");
        this.wordList.add("arsed");
        this.wordList.add("arsehole");
        this.wordList.add("arseholed");
        this.wordList.add("arseholes");
        this.wordList.add("arseholing");
        this.wordList.add("arselicker");
        this.wordList.add("arses");
        this.wordList.add("Ass");
        this.wordList.add("asshat");
        this.wordList.add("asshole");
        this.wordList.add("Auschwitz");
        this.wordList.add("b00bz");
        this.wordList.add("b1tc");
        this.wordList.add("Baise");
        this.wordList.add("bakachon");
        this.wordList.add("bakatyon");
        this.wordList.add("Ballsack");
        this.wordList.add("BAMF");
        this.wordList.add("Bastard");
        this.wordList.add("Beaner");
        this.wordList.add("Beeatch");
        this.wordList.add("beeeyotch");
        this.wordList.add("beefwhistle");
        this.wordList.add("beeotch");
        this.wordList.add("Beetch");
        this.wordList.add("beeyotch");
        this.wordList.add("Bellend");
        this.wordList.add("bestiality");
        this.wordList.add("beyitch");
        this.wordList.add("beyotch");
        this.wordList.add("Biach");
        this.wordList.add("bin laden");
        this.wordList.add("binladen");
        this.wordList.add("biotch");
        this.wordList.add("bitch");
        this.wordList.add("Bitching");
        this.wordList.add("blad");
        this.wordList.add("bladt");
        this.wordList.add("blowjob");
        this.wordList.add("blowme");
        this.wordList.add("blyad");
        this.wordList.add("blyadt");
        this.wordList.add("bon3r");
        this.wordList.add("boner");
        this.wordList.add("boobs");
        this.wordList.add("Btch");
        this.wordList.add("Bukakke");
        this.wordList.add("Bullshit");
        this.wordList.add("bung");
        this.wordList.add("butagorosi");
        this.wordList.add("butthead");
        this.wordList.add("Butthole");
        this.wordList.add("Buttplug");
        this.wordList.add("c0ck");
        this.wordList.add("Cabron");
        this.wordList.add("Cacca");
        this.wordList.add("Cadela");
        this.wordList.add("Cagada");
        this.wordList.add("Cameljockey");
        this.wordList.add("Caralho");
        this.wordList.add("castrate");
        this.wordList.add("Cazzo");
        this.wordList.add("ceemen");
        this.wordList.add("ch1nk");
        this.wordList.add("chankoro");
        this.wordList.add("chieokure");
        this.wordList.add("chikusatsu");
        this.wordList.add("Ching chong");
        this.wordList.add("Chinga");
        this.wordList.add("Chingada Madre");
        this.wordList.add("Chingado");
        this.wordList.add("Chingate");
        this.wordList.add("chink");
        this.wordList.add("chinpo");
        this.wordList.add("Chlamydia");
        this.wordList.add("choad");
        this.wordList.add("chode");
        this.wordList.add("chonga");
        this.wordList.add("chonko");
        this.wordList.add("chonkoro");
        this.wordList.add("chourimbo");
        this.wordList.add("chourinbo");
        this.wordList.add("chourippo");
        this.wordList.add("chuurembo");
        this.wordList.add("chuurenbo");
        this.wordList.add("circlejerk");
        this.wordList.add("cl1t");
        this.wordList.add("cli7");
        this.wordList.add("clit");
        this.wordList.add("clitoris");
        this.wordList.add("cocain");
        this.wordList.add("Cocaine");
        this.wordList.add("cock");
        this.wordList.add("Cocksucker");
        this.wordList.add("Coglione");
        this.wordList.add("Coglioni");
        this.wordList.add("coitus");
        this.wordList.add("coituss");
        this.wordList.add("cojelon");
        this.wordList.add("cojones");
        this.wordList.add("condom");
        this.wordList.add("coon");
        this.wordList.add("coon hunt");
        this.wordList.add("coon kill");
        this.wordList.add("coonhunt");
        this.wordList.add("coonkill");
        this.wordList.add("Cooter");
        this.wordList.add("cotton pic");
        this.wordList.add("cotton pik");
        this.wordList.add("cottonpic");
        this.wordList.add("cottonpik");
        this.wordList.add("Crackhead");
        this.wordList.add("CSAM");
        this.wordList.add("Culear");
        this.wordList.add("Culero");
        this.wordList.add("Culo");
        this.wordList.add("Cum");
        this.wordList.add("cun7");
        this.wordList.add("cunt");
        this.wordList.add("cvn7");
        this.wordList.add("cvnt");
        this.wordList.add("cyka");
        this.wordList.add("d1kc");
        this.wordList.add("d4go");
        this.wordList.add("dago");
        this.wordList.add("Darkie");
        this.wordList.add("Darkie");
        this.wordList.add("Deez Nuts");
        this.wordList.add("deeznut");
        this.wordList.add("deeznuts");
        this.wordList.add("Dickhead");
        this.wordList.add("dikc");
        this.wordList.add("dildo");
        this.wordList.add("Dio Bestia");
        this.wordList.add("dong");
        this.wordList.add("dongs");
        this.wordList.add("douche");
        this.wordList.add("Downie");
        this.wordList.add("Downy");
        this.wordList.add("Dumbass");
        this.wordList.add("Durka durka");
        this.wordList.add("Dyke");
        this.wordList.add("Ejaculate");
        this.wordList.add("Encule");
        this.wordList.add("enjokousai");
        this.wordList.add("enzyokousai");
        this.wordList.add("etahinin");
        this.wordList.add("etambo");
        this.wordList.add("etanbo");
        this.wordList.add("f0ck");
        this.wordList.add("f0kc");
        this.wordList.add("f3lch");
        this.wordList.add("facking");
        this.wordList.add("fag");
        this.wordList.add("faggot");
        this.wordList.add("Fanculo");
        this.wordList.add("Fanny");
        this.wordList.add("fatass");
        this.wordList.add("fck");
        this.wordList.add("Fckn");
        this.wordList.add("fcuk");
        this.wordList.add("fcuuk");
        this.wordList.add("felch");
        this.wordList.add("Fetish");
        this.wordList.add("Fgt");
        this.wordList.add("FiCKDiCH");
        this.wordList.add("Figlio di Puttana");
        this.wordList.add("fku");
        this.wordList.add("fock");
        this.wordList.add("fokc");
        this.wordList.add("foreskin");
        this.wordList.add("Fotze");
        this.wordList.add("Foutre");
        this.wordList.add("fucc");
        this.wordList.add("fuck");
        this.wordList.add("Fucking");
        this.wordList.add("fuct");
        this.wordList.add("fujinoyamai");
        this.wordList.add("fukashokumin");
        this.wordList.add("Fupa");
        this.wordList.add("fuuck");
        this.wordList.add("fuuuck");
        this.wordList.add("fuuuuck");
        this.wordList.add("fuuuuuck");
        this.wordList.add("fuuuuuuck");
        this.wordList.add("fuuuuuuuck");
        this.wordList.add("fuuuuuuuuck");
        this.wordList.add("fuuuuuuuuuck");
        this.wordList.add("fuuuuuuuuuu");
        this.wordList.add("fvck");
        this.wordList.add("fxck");
        this.wordList.add("fxuxcxk");
        this.wordList.add("g000k");
        this.wordList.add("g00k");
        this.wordList.add("g0ok");
        this.wordList.add("gestapo");
        this.wordList.add("go0k");
        this.wordList.add("god damn");
        this.wordList.add("goldenshowers");
        this.wordList.add("golliwogg");
        this.wordList.add("gollywog");
        this.wordList.add("Gooch");
        this.wordList.add("gook");
        this.wordList.add("goook");
        this.wordList.add("Gyp");
        this.wordList.add("h0m0");
        this.wordList.add("h0mo");
        this.wordList.add("h1tl3");
        this.wordList.add("h1tle");
        this.wordList.add("hairpie");
        this.wordList.add("hakujakusha");
        this.wordList.add("hakuroubyo");
        this.wordList.add("hakuzyakusya");
        this.wordList.add("hantoujin");
        this.wordList.add("hantouzin");
        this.wordList.add("Herpes");
        this.wordList.add("hitl3r");
        this.wordList.add("hitler");
        this.wordList.add("hitlr");
        this.wordList.add("holocaust");
        this.wordList.add("hom0");
        this.wordList.add("homo");
        this.wordList.add("honky");
        this.wordList.add("Hooker");
        this.wordList.add("hor3");
        this.wordList.add("hukasyokumin");
        this.wordList.add("Hure");
        this.wordList.add("Hurensohn");
        this.wordList.add("huzinoyamai");
        this.wordList.add("hymen");
        this.wordList.add("inc3st");
        this.wordList.add("incest");
        this.wordList.add("Inculato");
        this.wordList.add("Injun");
        this.wordList.add("intercourse");
        this.wordList.add("inugoroshi");
        this.wordList.add("inugorosi");
        this.wordList.add("j1g4b0");
        this.wordList.add("j1g4bo");
        this.wordList.add("j1gab0");
        this.wordList.add("j1gabo");
        this.wordList.add("Jack Off");
        this.wordList.add("jackass");
        this.wordList.add("jap");
        this.wordList.add("JerkOff");
        this.wordList.add("jig4b0");
        this.wordList.add("jig4bo");
        this.wordList.add("jigabo");
        this.wordList.add("Jigaboo");
        this.wordList.add("jiggaboo");
        this.wordList.add("jizz");
        this.wordList.add("Joder");
        this.wordList.add("Joto");
        this.wordList.add("Jungle Bunny");
        this.wordList.add("junglebunny");
        this.wordList.add("k k k");
        this.wordList.add("k1k3");
        this.wordList.add("kichigai");
        this.wordList.add("kik3");
        this.wordList.add("Kike");
        this.wordList.add("kikeiji");
        this.wordList.add("kikeizi");
        this.wordList.add("Kilurself");
        this.wordList.add("kitigai");
        this.wordList.add("kkk");
        this.wordList.add("klu klux");
        this.wordList.add("Klu Klux Klan");
        this.wordList.add("kluklux");
        this.wordList.add("knobhead");
        this.wordList.add("koon hunt");
        this.wordList.add("koon kill");
        this.wordList.add("koonhunt");
        this.wordList.add("koonkill");
        this.wordList.add("koroshiteyaru");
        this.wordList.add("koumoujin");
        this.wordList.add("koumouzin");
        this.wordList.add("ku klux klan");
        this.wordList.add("kun7");
        this.wordList.add("kurombo");
        this.wordList.add("Kurva");
        this.wordList.add("Kurwa");
        this.wordList.add("kxkxk");
        this.wordList.add("l3sb0");
        this.wordList.add("lezbo");
        this.wordList.add("lezzie");
        this.wordList.add("m07th3rfukr");
        this.wordList.add("m0th3rfvk3r");
        this.wordList.add("m0th3rfvker");
        this.wordList.add("Madonna Puttana");
        this.wordList.add("manberries");
        this.wordList.add("manko");
        this.wordList.add("manshaft");
        this.wordList.add("Maricon");
        this.wordList.add("Masterbat");
        this.wordList.add("masterbate");
        this.wordList.add("Masturbacion");
        this.wordList.add("masturbait");
        this.wordList.add("Masturbare");
        this.wordList.add("Masturbate");
        this.wordList.add("Masturbazione");
        this.wordList.add("Merda");
        this.wordList.add("Merde");
        this.wordList.add("Meth");
        this.wordList.add("Mierda");
        this.wordList.add("milf");
        this.wordList.add("Minge");
        this.wordList.add("Miststück");
        this.wordList.add("mitsukuchi");
        this.wordList.add("mitukuti");
        this.wordList.add("Molest");
        this.wordList.add("molester");
        this.wordList.add("molestor");
        this.wordList.add("Mong");
        this.wordList.add("Moon Cricket");
        this.wordList.add("moth3rfucer");
        this.wordList.add("moth3rfvk3r");
        this.wordList.add("moth3rfvker");
        this.wordList.add("motherfucker");
        this.wordList.add("Mulatto");
        this.wordList.add("n1663r");
        this.wordList.add("n1664");
        this.wordList.add("n166a");
        this.wordList.add("n166er");
        this.wordList.add("n1g3r");
        this.wordList.add("n1German");
        this.wordList.add("n1gg3r");
        this.wordList.add("n1gGerman");
        this.wordList.add("n3gro");
        this.wordList.add("n4g3r");
        this.wordList.add("n4gg3r");
        this.wordList.add("n4gGerman");
        this.wordList.add("n4z1");
        this.wordList.add("nag3r");
        this.wordList.add("nagg3r");
        this.wordList.add("nagGerman");
        this.wordList.add("natzi");
        this.wordList.add("naz1");
        this.wordList.add("nazi");
        this.wordList.add("nazl");
        this.wordList.add("neGerman");
        this.wordList.add("ngGerman");
        this.wordList.add("nggr");
        this.wordList.add("NhigGerman");
        this.wordList.add("ni666");
        this.wordList.add("ni66a");
        this.wordList.add("ni66er");
        this.wordList.add("ni66g");
        this.wordList.add("ni6g");
        this.wordList.add("ni6g6");
        this.wordList.add("ni6gg");
        this.wordList.add("Nig");
        this.wordList.add("nig66");
        this.wordList.add("nig6g");
        this.wordList.add("nigar");
        this.wordList.add("niGerman");
        this.wordList.add("nigg3");
        this.wordList.add("nigg6");
        this.wordList.add("nigga");
        this.wordList.add("niggaz");
        this.wordList.add("nigGerman");
        this.wordList.add("nigglet");
        this.wordList.add("niggr");
        this.wordList.add("nigguh");
        this.wordList.add("niggur");
        this.wordList.add("niggy");
        this.wordList.add("niglet");
        this.wordList.add("Nignog");
        this.wordList.add("nimpinin");
        this.wordList.add("ninpinin");
        this.wordList.add("Nipples");
        this.wordList.add("niqqa");
        this.wordList.add("niqqer");
        this.wordList.add("Nonce");
        this.wordList.add("nugga");
        this.wordList.add("Nutsack");
        this.wordList.add("Nutted");
        this.wordList.add("nygGerman");
        this.wordList.add("omeko");
        this.wordList.add("Orgy");
        this.wordList.add("p3n15");
        this.wordList.add("p3n1s");
        this.wordList.add("p3ni5");
        this.wordList.add("p3nis");
        this.wordList.add("p3nl5");
        this.wordList.add("p3nls");
        this.wordList.add("Paki");
        this.wordList.add("Panties");
        this.wordList.add("Pedo");
        this.wordList.add("pedoph");
        this.wordList.add("pedophile");
        this.wordList.add("pen15");
        this.wordList.add("pen1s");
        this.wordList.add("Pendejo");
        this.wordList.add("peni5");
        this.wordList.add("penile");
        this.wordList.add("penis");
        this.wordList.add("Penis");
        this.wordList.add("penl5");
        this.wordList.add("penls");
        this.wordList.add("penus");
        this.wordList.add("Perra");
        this.wordList.add("phaggot");
        this.wordList.add("phagot");
        this.wordList.add("phuck");
        this.wordList.add("Pikey");
        this.wordList.add("Pinche");
        this.wordList.add("Pizda");
        this.wordList.add("Polla");
        this.wordList.add("Porca Madonna");
        this.wordList.add("Porch monkey");
        this.wordList.add("Porn");
        this.wordList.add("Porra");
        this.wordList.add("pr1ck");
        this.wordList.add("preteen");
        this.wordList.add("prick");
        this.wordList.add("pu555y");
        this.wordList.add("pu55y");
        this.wordList.add("pub1c");
        this.wordList.add("Pube");
        this.wordList.add("pubic");
        this.wordList.add("pun4ni");
        this.wordList.add("pun4nl");
        this.wordList.add("Punal");
        this.wordList.add("punan1");
        this.wordList.add("punani");
        this.wordList.add("punanl");
        this.wordList.add("puss1");
        this.wordList.add("puss3");
        this.wordList.add("puss5");
        this.wordList.add("pusse");
        this.wordList.add("pussi");
        this.wordList.add("Pussies");
        this.wordList.add("pusss1");
        this.wordList.add("pussse");
        this.wordList.add("pusssi");
        this.wordList.add("pusssl");
        this.wordList.add("pusssy");
        this.wordList.add("Pussy");
        this.wordList.add("Puta");
        this.wordList.add("Putain");
        this.wordList.add("Pute");
        this.wordList.add("Puto");
        this.wordList.add("Puttana");
        this.wordList.add("Puttane");
        this.wordList.add("Puttaniere");
        this.wordList.add("puzzy");
        this.wordList.add("pvssy");
        this.wordList.add("queef");
        this.wordList.add("r3c7um");
        this.wordList.add("r4p15t");
        this.wordList.add("r4p1st");
        this.wordList.add("r4p3");
        this.wordList.add("r4pi5t");
        this.wordList.add("r4pist");
        this.wordList.add("raape");
        this.wordList.add("raghead");
        this.wordList.add("raibyo");
        this.wordList.add("Raip");
        this.wordList.add("rap15t");
        this.wordList.add("rap1st");
        this.wordList.add("Rapage");
        this.wordList.add("rape");
        this.wordList.add("Raped");
        this.wordList.add("rapi5t");
        this.wordList.add("Raping");
        this.wordList.add("rapist");
        this.wordList.add("rectum");
        this.wordList.add("Red Tube");
        this.wordList.add("Reggin");
        this.wordList.add("reipu");
        this.wordList.add("retard");
        this.wordList.add("Ricchione");
        this.wordList.add("rimjob");
        this.wordList.add("rizzape");
        this.wordList.add("rompari");
        this.wordList.add("Salaud");
        this.wordList.add("Salope");
        this.wordList.add("sangokujin");
        this.wordList.add("sangokuzin");
        this.wordList.add("santorum");
        this.wordList.add("Scheiße");
        this.wordList.add("Schlampe");
        this.wordList.add("Schlampe");
        this.wordList.add("schlong");
        this.wordList.add("Schwuchtel");
        this.wordList.add("Scrote");
        this.wordList.add("secks");
        this.wordList.add("seishinhakujaku");
        this.wordList.add("seishinijo");
        this.wordList.add("seisinhakuzyaku");
        this.wordList.add("seisinizyo");
        this.wordList.add("Semen");
        this.wordList.add("semushiotoko");
        this.wordList.add("semusiotoko");
        this.wordList.add("sh|t");
        this.wordList.add("sh17");
        this.wordList.add("sh1t");
        this.wordList.add("Shemae");
        this.wordList.add("Shat");
        this.wordList.add("shi7");
        this.wordList.add("shinajin");
        this.wordList.add("shinheimin");
        this.wordList.add("shirakko");
        this.wordList.add("shit");
        this.wordList.add("Shitty");
        this.wordList.add("shl7");
        this.wordList.add("shlt");
        this.wordList.add("shokubutsuningen");
        this.wordList.add("sinazin");
        this.wordList.add("sinheimin");
        this.wordList.add("Skank");
        this.wordList.add("SMD");
        this.wordList.add("Sodom");
        this.wordList.add("sofa king");
        this.wordList.add("sofaking");
        this.wordList.add("Spanishick");
        this.wordList.add("Spanishook");
        this.wordList.add("Spanishunk");
        this.wordList.add("STD");
        this.wordList.add("STDs");
        this.wordList.add("Succhia Cazzi");
        this.wordList.add("suck my");
        this.wordList.add("suckmy");
        this.wordList.add("syokubutuningen");
        this.wordList.add("Taint");
        this.wordList.add("Tapatte");
        this.wordList.add("Tapette");
        this.wordList.add("Tarlouse");
        this.wordList.add("tea bag");
        this.wordList.add("teabag");
        this.wordList.add("teebag");
        this.wordList.add("teensex");
        this.wordList.add("teino");
        this.wordList.add("Testa di Cazzo");
        this.wordList.add("Testicles");
        this.wordList.add("Thot");
        this.wordList.add("tieokure");
        this.wordList.add("tinpo");
        this.wordList.add("Tits");
        this.wordList.add("tokushugakkyu");
        this.wordList.add("tokusyugakkyu");
        this.wordList.add("torukoburo");
        this.wordList.add("torukojo");
        this.wordList.add("torukozyo");
        this.wordList.add("tosatsu");
        this.wordList.add("tosatu");
        this.wordList.add("towelhead");
        this.wordList.add("Tranny");
        this.wordList.add("tunbo");
        this.wordList.add("tw47");
        this.wordList.add("tw4t");
        this.wordList.add("twat");
        this.wordList.add("tyankoro");
        this.wordList.add("tyonga");
        this.wordList.add("tyonko");
        this.wordList.add("tyonkoro");
        this.wordList.add("tyourinbo");
        this.wordList.add("tyourippo");
        this.wordList.add("tyurenbo");
        this.wordList.add("ushigoroshi");
        this.wordList.add("usigorosi");
        this.wordList.add("v461n4");
        this.wordList.add("v461na");
        this.wordList.add("v46in4");
        this.wordList.add("v46ina");
        this.wordList.add("v4g1n4");
        this.wordList.add("v4g1na");
        this.wordList.add("v4gin4");
        this.wordList.add("v4gina");
        this.wordList.add("va61n4");
        this.wordList.add("va61na");
        this.wordList.add("va6in4");
        this.wordList.add("va6ina");
        this.wordList.add("Vaccagare");
        this.wordList.add("Vaffanculo");
        this.wordList.add("Vag");
        this.wordList.add("vag1n4");
        this.wordList.add("vag1na");
        this.wordList.add("vagin4");
        this.wordList.add("vagina");
        this.wordList.add("VateFaire");
        this.wordList.add("vvhitepower");
        this.wordList.add("w3tb4ck");
        this.wordList.add("w3tback");
        this.wordList.add("Wank");
        this.wordList.add("wanker");
        this.wordList.add("wetb4ck");
        this.wordList.add("wetback");
        this.wordList.add("wh0r3");
        this.wordList.add("wh0re");
        this.wordList.add("white power");
        this.wordList.add("whitepower");
        this.wordList.add("whor3");
        this.wordList.add("whore");
        this.wordList.add("Wog");
        this.wordList.add("Wop");
        this.wordList.add("x8lp3t");
        this.wordList.add("xbl pet");
        this.wordList.add("XBLPET");
        this.wordList.add("XBLRewards");
        this.wordList.add("Xl3LPET");
        this.wordList.add("yabunirami");
        this.wordList.add("Zipperhead");
        this.wordList.add("Блядь");
        this.wordList.add("сука");
        this.wordList.add("アオカン");
        this.wordList.add("あおかん");
        this.wordList.add("イヌゴロシ");
        this.wordList.add("いぬごろし");
        this.wordList.add("インバイ");
        this.wordList.add("いんばい");
        this.wordList.add("オナニー");
        this.wordList.add("オナニー");
        this.wordList.add("オメコ");
        this.wordList.add("カワラコジキ");
        this.wordList.add("かわらこじき");
        this.wordList.add("かわらこじき");
        this.wordList.add("かわらもの");
        this.wordList.add("キケイジ");
        this.wordList.add("きけいじ");
        this.wordList.add("キチガイ");
        this.wordList.add("きちがい");
        this.wordList.add("キンタマ");
        this.wordList.add("きんたま");
        this.wordList.add("クロンボ");
        this.wordList.add("くろんぼ");
        this.wordList.add("コロシテヤル");
        this.wordList.add("ころしてやる");
        this.wordList.add("シナジン");
        this.wordList.add("しなじん");
        this.wordList.add("タチンボ");
        this.wordList.add("たちんぼ");
        this.wordList.add("チョンコウ");
        this.wordList.add("ちょんこう");
        this.wordList.add("ちょんこう");
        this.wordList.add("チョンコロ");
        this.wordList.add("ちょんころ");
        this.wordList.add("ちょん公");
        this.wordList.add("チンポ");
        this.wordList.add("ちんぽ");
        this.wordList.add("ツンボ");
        this.wordList.add("つんぼ");
        this.wordList.add("とるこじょう");
        this.wordList.add("とるこぶろ");
        this.wordList.add("トルコ嬢");
        this.wordList.add("トルコ風呂");
        this.wordList.add("ニガー");
        this.wordList.add("ニグロ");
        this.wordList.add("にんぴにん");
        this.wordList.add("はんとうじん");
        this.wordList.add("マンコ");
        this.wordList.add("まんこ");
        this.wordList.add("レイプ");
        this.wordList.add("れいぷ");
        this.wordList.add("低能");
        this.wordList.add("屠殺");
        this.wordList.add("強姦");
        this.wordList.add("援交");
        this.wordList.add("支那人");
        this.wordList.add("精薄");
        this.wordList.add("精薄者");
        this.wordList.add("輪姦");
    }

    @Subscribe(order = PostOrder.FIRST)
    public void onPlayerChat(PlayerChatEvent event) {
        Player player = event.getPlayer();
        String message = event.getMessage();

        // Word Filter
        for (String word : wordList) {
            if (message.toLowerCase().contains(word.toLowerCase())) {
                message = message.replaceAll("(?i)" + word, "*".repeat(word.length()));
            }
        }

        Utils.broadcast(this.proxyServer, player, Component.text(message));
    }

}
