package dev.ursinn.velocity.nici.management.modules;

import com.velocitypowered.api.event.PostOrder;
import com.velocitypowered.api.event.Subscribe;
import com.velocitypowered.api.event.player.PlayerChatEvent;
import com.velocitypowered.api.proxy.Player;
import com.velocitypowered.api.proxy.ProxyServer;
import com.velocitypowered.api.proxy.ServerConnection;
import com.velocitypowered.api.proxy.server.RegisteredServer;
import dev.ursinn.velocity.nici.management.Utils;
import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.TextComponent;
import org.slf4j.Logger;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

public class Message {

    private final ProxyServer proxyServer;
    private final List<String> wordList;

    public Message(ProxyServer proxyServer, Logger logger) {
        this.proxyServer = proxyServer;
        this.wordList = new ArrayList<>();

        initWordList();
        logger.info("Loaded Message.");
    }

    private void initWordList() {
        wordList.add("1488");
        wordList.add("8=D");
        wordList.add("A55hole");
        wordList.add("abortion");
        wordList.add("ahole");
        wordList.add("AIDs");
        wordList.add("ainujin");
        wordList.add("ainuzin");
        wordList.add("akimekura");
        wordList.add("Anal");
        wordList.add("anus");
        wordList.add("anuses");
        wordList.add("Anushead");
        wordList.add("anuslick");
        wordList.add("anuss");
        wordList.add("aokan");
        wordList.add("Arsch");
        wordList.add("Arschloch");
        wordList.add("arse");
        wordList.add("arsed");
        wordList.add("arsehole");
        wordList.add("arseholed");
        wordList.add("arseholes");
        wordList.add("arseholing");
        wordList.add("arselicker");
        wordList.add("arses");
        wordList.add("Ass");
        wordList.add("asshat");
        wordList.add("asshole");
        wordList.add("Auschwitz");
        wordList.add("b00bz");
        wordList.add("b1tc");
        wordList.add("Baise");
        wordList.add("bakachon");
        wordList.add("bakatyon");
        wordList.add("Ballsack");
        wordList.add("BAMF");
        wordList.add("Bastard");
        wordList.add("Beaner");
        wordList.add("Beeatch");
        wordList.add("beeeyotch");
        wordList.add("beefwhistle");
        wordList.add("beeotch");
        wordList.add("Beetch");
        wordList.add("beeyotch");
        wordList.add("Bellend");
        wordList.add("bestiality");
        wordList.add("beyitch");
        wordList.add("beyotch");
        wordList.add("Biach");
        wordList.add("bin laden");
        wordList.add("binladen");
        wordList.add("biotch");
        wordList.add("bitch");
        wordList.add("Bitching");
        wordList.add("blad");
        wordList.add("bladt");
        wordList.add("blowjob");
        wordList.add("blowme");
        wordList.add("blyad");
        wordList.add("blyadt");
        wordList.add("bon3r");
        wordList.add("boner");
        wordList.add("boobs");
        wordList.add("Btch");
        wordList.add("Bukakke");
        wordList.add("Bullshit");
        wordList.add("bung");
        wordList.add("butagorosi");
        wordList.add("butthead");
        wordList.add("Butthole");
        wordList.add("Buttplug");
        wordList.add("c0ck");
        wordList.add("Cabron");
        wordList.add("Cacca");
        wordList.add("Cadela");
        wordList.add("Cagada");
        wordList.add("Cameljockey");
        wordList.add("Caralho");
        wordList.add("castrate");
        wordList.add("Cazzo");
        wordList.add("ceemen");
        wordList.add("ch1nk");
        wordList.add("chankoro");
        wordList.add("chieokure");
        wordList.add("chikusatsu");
        wordList.add("Ching chong");
        wordList.add("Chinga");
        wordList.add("Chingada Madre");
        wordList.add("Chingado");
        wordList.add("Chingate");
        wordList.add("chink");
        wordList.add("chinpo");
        wordList.add("Chlamydia");
        wordList.add("choad");
        wordList.add("chode");
        wordList.add("chonga");
        wordList.add("chonko");
        wordList.add("chonkoro");
        wordList.add("chourimbo");
        wordList.add("chourinbo");
        wordList.add("chourippo");
        wordList.add("chuurembo");
        wordList.add("chuurenbo");
        wordList.add("circlejerk");
        wordList.add("cl1t");
        wordList.add("cli7");
        wordList.add("clit");
        wordList.add("clitoris");
        wordList.add("cocain");
        wordList.add("Cocaine");
        wordList.add("cock");
        wordList.add("Cocksucker");
        wordList.add("Coglione");
        wordList.add("Coglioni");
        wordList.add("coitus");
        wordList.add("coituss");
        wordList.add("cojelon");
        wordList.add("cojones");
        wordList.add("condom");
        wordList.add("coon");
        wordList.add("coon hunt");
        wordList.add("coon kill");
        wordList.add("coonhunt");
        wordList.add("coonkill");
        wordList.add("Cooter");
        wordList.add("cotton pic");
        wordList.add("cotton pik");
        wordList.add("cottonpic");
        wordList.add("cottonpik");
        wordList.add("Crackhead");
        wordList.add("CSAM");
        wordList.add("Culear");
        wordList.add("Culero");
        wordList.add("Culo");
        wordList.add("Cum");
        wordList.add("cun7");
        wordList.add("cunt");
        wordList.add("cvn7");
        wordList.add("cvnt");
        wordList.add("cyka");
        wordList.add("d1kc");
        wordList.add("d4go");
        wordList.add("dago");
        wordList.add("Darkie");
        wordList.add("Darkie");
        wordList.add("Deez Nuts");
        wordList.add("deeznut");
        wordList.add("deeznuts");
        wordList.add("Dickhead");
        wordList.add("dikc");
        wordList.add("dildo");
        wordList.add("Dio Bestia");
        wordList.add("dong");
        wordList.add("dongs");
        wordList.add("douche");
        wordList.add("Downie");
        wordList.add("Downy");
        wordList.add("Dumbass");
        wordList.add("Durka durka");
        wordList.add("Dyke");
        wordList.add("Ejaculate");
        wordList.add("Encule");
        wordList.add("enjokousai");
        wordList.add("enzyokousai");
        wordList.add("etahinin");
        wordList.add("etambo");
        wordList.add("etanbo");
        wordList.add("f0ck");
        wordList.add("f0kc");
        wordList.add("f3lch");
        wordList.add("facking");
        wordList.add("fag");
        wordList.add("faggot");
        wordList.add("Fanculo");
        wordList.add("Fanny");
        wordList.add("fatass");
        wordList.add("fck");
        wordList.add("Fckn");
        wordList.add("fcuk");
        wordList.add("fcuuk");
        wordList.add("felch");
        wordList.add("Fetish");
        wordList.add("Fgt");
        wordList.add("FiCKDiCH");
        wordList.add("Figlio di Puttana");
        wordList.add("fku");
        wordList.add("fock");
        wordList.add("fokc");
        wordList.add("foreskin");
        wordList.add("Fotze");
        wordList.add("Foutre");
        wordList.add("fucc");
        wordList.add("fuck");
        wordList.add("Fucking");
        wordList.add("fuct");
        wordList.add("fujinoyamai");
        wordList.add("fukashokumin");
        wordList.add("Fupa");
        wordList.add("fuuck");
        wordList.add("fuuuck");
        wordList.add("fuuuuck");
        wordList.add("fuuuuuck");
        wordList.add("fuuuuuuck");
        wordList.add("fuuuuuuuck");
        wordList.add("fuuuuuuuuck");
        wordList.add("fuuuuuuuuuck");
        wordList.add("fuuuuuuuuuu");
        wordList.add("fvck");
        wordList.add("fxck");
        wordList.add("fxuxcxk");
        wordList.add("g000k");
        wordList.add("g00k");
        wordList.add("g0ok");
        wordList.add("gestapo");
        wordList.add("go0k");
        wordList.add("god damn");
        wordList.add("goldenshowers");
        wordList.add("golliwogg");
        wordList.add("gollywog");
        wordList.add("Gooch");
        wordList.add("gook");
        wordList.add("goook");
        wordList.add("Gyp");
        wordList.add("h0m0");
        wordList.add("h0mo");
        wordList.add("h1tl3");
        wordList.add("h1tle");
        wordList.add("hairpie");
        wordList.add("hakujakusha");
        wordList.add("hakuroubyo");
        wordList.add("hakuzyakusya");
        wordList.add("hantoujin");
        wordList.add("hantouzin");
        wordList.add("Herpes");
        wordList.add("hitl3r");
        wordList.add("hitler");
        wordList.add("hitlr");
        wordList.add("holocaust");
        wordList.add("hom0");
        wordList.add("homo");
        wordList.add("honky");
        wordList.add("Hooker");
        wordList.add("hor3");
        wordList.add("hukasyokumin");
        wordList.add("Hure");
        wordList.add("Hurensohn");
        wordList.add("huzinoyamai");
        wordList.add("hymen");
        wordList.add("inc3st");
        wordList.add("incest");
        wordList.add("Inculato");
        wordList.add("Injun");
        wordList.add("intercourse");
        wordList.add("inugoroshi");
        wordList.add("inugorosi");
        wordList.add("j1g4b0");
        wordList.add("j1g4bo");
        wordList.add("j1gab0");
        wordList.add("j1gabo");
        wordList.add("Jack Off");
        wordList.add("jackass");
        wordList.add("jap");
        wordList.add("JerkOff");
        wordList.add("jig4b0");
        wordList.add("jig4bo");
        wordList.add("jigabo");
        wordList.add("Jigaboo");
        wordList.add("jiggaboo");
        wordList.add("jizz");
        wordList.add("Joder");
        wordList.add("Joto");
        wordList.add("Jungle Bunny");
        wordList.add("junglebunny");
        wordList.add("k k k");
        wordList.add("k1k3");
        wordList.add("kichigai");
        wordList.add("kik3");
        wordList.add("Kike");
        wordList.add("kikeiji");
        wordList.add("kikeizi");
        wordList.add("Kilurself");
        wordList.add("kitigai");
        wordList.add("kkk");
        wordList.add("klu klux");
        wordList.add("Klu Klux Klan");
        wordList.add("kluklux");
        wordList.add("knobhead");
        wordList.add("koon hunt");
        wordList.add("koon kill");
        wordList.add("koonhunt");
        wordList.add("koonkill");
        wordList.add("koroshiteyaru");
        wordList.add("koumoujin");
        wordList.add("koumouzin");
        wordList.add("ku klux klan");
        wordList.add("kun7");
        wordList.add("kurombo");
        wordList.add("Kurva");
        wordList.add("Kurwa");
        wordList.add("kxkxk");
        wordList.add("l3sb0");
        wordList.add("lezbo");
        wordList.add("lezzie");
        wordList.add("m07th3rfukr");
        wordList.add("m0th3rfvk3r");
        wordList.add("m0th3rfvker");
        wordList.add("Madonna Puttana");
        wordList.add("manberries");
        wordList.add("manko");
        wordList.add("manshaft");
        wordList.add("Maricon");
        wordList.add("Masterbat");
        wordList.add("masterbate");
        wordList.add("Masturbacion");
        wordList.add("masturbait");
        wordList.add("Masturbare");
        wordList.add("Masturbate");
        wordList.add("Masturbazione");
        wordList.add("Merda");
        wordList.add("Merde");
        wordList.add("Meth");
        wordList.add("Mierda");
        wordList.add("milf");
        wordList.add("Minge");
        wordList.add("Miststück");
        wordList.add("mitsukuchi");
        wordList.add("mitukuti");
        wordList.add("Molest");
        wordList.add("molester");
        wordList.add("molestor");
        wordList.add("Mong");
        wordList.add("Moon Cricket");
        wordList.add("moth3rfucer");
        wordList.add("moth3rfvk3r");
        wordList.add("moth3rfvker");
        wordList.add("motherfucker");
        wordList.add("Mulatto");
        wordList.add("n1663r");
        wordList.add("n1664");
        wordList.add("n166a");
        wordList.add("n166er");
        wordList.add("n1g3r");
        wordList.add("n1German");
        wordList.add("n1gg3r");
        wordList.add("n1gGerman");
        wordList.add("n3gro");
        wordList.add("n4g3r");
        wordList.add("n4gg3r");
        wordList.add("n4gGerman");
        wordList.add("n4z1");
        wordList.add("nag3r");
        wordList.add("nagg3r");
        wordList.add("nagGerman");
        wordList.add("natzi");
        wordList.add("naz1");
        wordList.add("nazi");
        wordList.add("nazl");
        wordList.add("neGerman");
        wordList.add("ngGerman");
        wordList.add("nggr");
        wordList.add("NhigGerman");
        wordList.add("ni666");
        wordList.add("ni66a");
        wordList.add("ni66er");
        wordList.add("ni66g");
        wordList.add("ni6g");
        wordList.add("ni6g6");
        wordList.add("ni6gg");
        wordList.add("Nig");
        wordList.add("nig66");
        wordList.add("nig6g");
        wordList.add("nigar");
        wordList.add("niGerman");
        wordList.add("nigg3");
        wordList.add("nigg6");
        wordList.add("nigga");
        wordList.add("niggaz");
        wordList.add("nigGerman");
        wordList.add("nigglet");
        wordList.add("niggr");
        wordList.add("nigguh");
        wordList.add("niggur");
        wordList.add("niggy");
        wordList.add("niglet");
        wordList.add("Nignog");
        wordList.add("nimpinin");
        wordList.add("ninpinin");
        wordList.add("Nipples");
        wordList.add("niqqa");
        wordList.add("niqqer");
        wordList.add("Nonce");
        wordList.add("nugga");
        wordList.add("Nutsack");
        wordList.add("Nutted");
        wordList.add("nygGerman");
        wordList.add("omeko");
        wordList.add("Orgy");
        wordList.add("p3n15");
        wordList.add("p3n1s");
        wordList.add("p3ni5");
        wordList.add("p3nis");
        wordList.add("p3nl5");
        wordList.add("p3nls");
        wordList.add("Paki");
        wordList.add("Panties");
        wordList.add("Pedo");
        wordList.add("pedoph");
        wordList.add("pedophile");
        wordList.add("pen15");
        wordList.add("pen1s");
        wordList.add("Pendejo");
        wordList.add("peni5");
        wordList.add("penile");
        wordList.add("penis");
        wordList.add("Penis");
        wordList.add("penl5");
        wordList.add("penls");
        wordList.add("penus");
        wordList.add("Perra");
        wordList.add("phaggot");
        wordList.add("phagot");
        wordList.add("phuck");
        wordList.add("Pikey");
        wordList.add("Pinche");
        wordList.add("Pizda");
        wordList.add("Polla");
        wordList.add("Porca Madonna");
        wordList.add("Porch monkey");
        wordList.add("Porn");
        wordList.add("Porra");
        wordList.add("pr1ck");
        wordList.add("preteen");
        wordList.add("prick");
        wordList.add("pu555y");
        wordList.add("pu55y");
        wordList.add("pub1c");
        wordList.add("Pube");
        wordList.add("pubic");
        wordList.add("pun4ni");
        wordList.add("pun4nl");
        wordList.add("Punal");
        wordList.add("punan1");
        wordList.add("punani");
        wordList.add("punanl");
        wordList.add("puss1");
        wordList.add("puss3");
        wordList.add("puss5");
        wordList.add("pusse");
        wordList.add("pussi");
        wordList.add("Pussies");
        wordList.add("pusss1");
        wordList.add("pussse");
        wordList.add("pusssi");
        wordList.add("pusssl");
        wordList.add("pusssy");
        wordList.add("Pussy");
        wordList.add("Puta");
        wordList.add("Putain");
        wordList.add("Pute");
        wordList.add("Puto");
        wordList.add("Puttana");
        wordList.add("Puttane");
        wordList.add("Puttaniere");
        wordList.add("puzzy");
        wordList.add("pvssy");
        wordList.add("queef");
        wordList.add("r3c7um");
        wordList.add("r4p15t");
        wordList.add("r4p1st");
        wordList.add("r4p3");
        wordList.add("r4pi5t");
        wordList.add("r4pist");
        wordList.add("raape");
        wordList.add("raghead");
        wordList.add("raibyo");
        wordList.add("Raip");
        wordList.add("rap15t");
        wordList.add("rap1st");
        wordList.add("Rapage");
        wordList.add("rape");
        wordList.add("Raped");
        wordList.add("rapi5t");
        wordList.add("Raping");
        wordList.add("rapist");
        wordList.add("rectum");
        wordList.add("Red Tube");
        wordList.add("Reggin");
        wordList.add("reipu");
        wordList.add("retard");
        wordList.add("Ricchione");
        wordList.add("rimjob");
        wordList.add("rizzape");
        wordList.add("rompari");
        wordList.add("Salaud");
        wordList.add("Salope");
        wordList.add("sangokujin");
        wordList.add("sangokuzin");
        wordList.add("santorum");
        wordList.add("Scheiße");
        wordList.add("Schlampe");
        wordList.add("Schlampe");
        wordList.add("schlong");
        wordList.add("Schwuchtel");
        wordList.add("Scrote");
        wordList.add("secks");
        wordList.add("seishinhakujaku");
        wordList.add("seishinijo");
        wordList.add("seisinhakuzyaku");
        wordList.add("seisinizyo");
        wordList.add("Semen");
        wordList.add("semushiotoko");
        wordList.add("semusiotoko");
        wordList.add("sh|t");
        wordList.add("sh17");
        wordList.add("sh1t");
        wordList.add("Shemae");
        wordList.add("Shat");
        wordList.add("shi7");
        wordList.add("shinajin");
        wordList.add("shinheimin");
        wordList.add("shirakko");
        wordList.add("shit");
        wordList.add("Shitty");
        wordList.add("shl7");
        wordList.add("shlt");
        wordList.add("shokubutsuningen");
        wordList.add("sinazin");
        wordList.add("sinheimin");
        wordList.add("Skank");
        wordList.add("SMD");
        wordList.add("Sodom");
        wordList.add("sofa king");
        wordList.add("sofaking");
        wordList.add("Spanishick");
        wordList.add("Spanishook");
        wordList.add("Spanishunk");
        wordList.add("STD");
        wordList.add("STDs");
        wordList.add("Succhia Cazzi");
        wordList.add("suck my");
        wordList.add("suckmy");
        wordList.add("syokubutuningen");
        wordList.add("Taint");
        wordList.add("Tapatte");
        wordList.add("Tapette");
        wordList.add("Tarlouse");
        wordList.add("tea bag");
        wordList.add("teabag");
        wordList.add("teebag");
        wordList.add("teensex");
        wordList.add("teino");
        wordList.add("Testa di Cazzo");
        wordList.add("Testicles");
        wordList.add("Thot");
        wordList.add("tieokure");
        wordList.add("tinpo");
        wordList.add("Tits");
        wordList.add("tokushugakkyu");
        wordList.add("tokusyugakkyu");
        wordList.add("torukoburo");
        wordList.add("torukojo");
        wordList.add("torukozyo");
        wordList.add("tosatsu");
        wordList.add("tosatu");
        wordList.add("towelhead");
        wordList.add("Tranny");
        wordList.add("tunbo");
        wordList.add("tw47");
        wordList.add("tw4t");
        wordList.add("twat");
        wordList.add("tyankoro");
        wordList.add("tyonga");
        wordList.add("tyonko");
        wordList.add("tyonkoro");
        wordList.add("tyourinbo");
        wordList.add("tyourippo");
        wordList.add("tyurenbo");
        wordList.add("ushigoroshi");
        wordList.add("usigorosi");
        wordList.add("v461n4");
        wordList.add("v461na");
        wordList.add("v46in4");
        wordList.add("v46ina");
        wordList.add("v4g1n4");
        wordList.add("v4g1na");
        wordList.add("v4gin4");
        wordList.add("v4gina");
        wordList.add("va61n4");
        wordList.add("va61na");
        wordList.add("va6in4");
        wordList.add("va6ina");
        wordList.add("Vaccagare");
        wordList.add("Vaffanculo");
        wordList.add("Vag");
        wordList.add("vag1n4");
        wordList.add("vag1na");
        wordList.add("vagin4");
        wordList.add("vagina");
        wordList.add("VateFaire");
        wordList.add("vvhitepower");
        wordList.add("w3tb4ck");
        wordList.add("w3tback");
        wordList.add("Wank");
        wordList.add("wanker");
        wordList.add("wetb4ck");
        wordList.add("wetback");
        wordList.add("wh0r3");
        wordList.add("wh0re");
        wordList.add("white power");
        wordList.add("whitepower");
        wordList.add("whor3");
        wordList.add("whore");
        wordList.add("Wog");
        wordList.add("Wop");
        wordList.add("x8lp3t");
        wordList.add("xbl pet");
        wordList.add("XBLPET");
        wordList.add("XBLRewards");
        wordList.add("Xl3LPET");
        wordList.add("yabunirami");
        wordList.add("Zipperhead");
        wordList.add("Блядь");
        wordList.add("сука");
        wordList.add("アオカン");
        wordList.add("あおかん");
        wordList.add("イヌゴロシ");
        wordList.add("いぬごろし");
        wordList.add("インバイ");
        wordList.add("いんばい");
        wordList.add("オナニー");
        wordList.add("オナニー");
        wordList.add("オメコ");
        wordList.add("カワラコジキ");
        wordList.add("かわらこじき");
        wordList.add("かわらこじき");
        wordList.add("かわらもの");
        wordList.add("キケイジ");
        wordList.add("きけいじ");
        wordList.add("キチガイ");
        wordList.add("きちがい");
        wordList.add("キンタマ");
        wordList.add("きんたま");
        wordList.add("クロンボ");
        wordList.add("くろんぼ");
        wordList.add("コロシテヤル");
        wordList.add("ころしてやる");
        wordList.add("シナジン");
        wordList.add("しなじん");
        wordList.add("タチンボ");
        wordList.add("たちんぼ");
        wordList.add("チョンコウ");
        wordList.add("ちょんこう");
        wordList.add("ちょんこう");
        wordList.add("チョンコロ");
        wordList.add("ちょんころ");
        wordList.add("ちょん公");
        wordList.add("チンポ");
        wordList.add("ちんぽ");
        wordList.add("ツンボ");
        wordList.add("つんぼ");
        wordList.add("とるこじょう");
        wordList.add("とるこぶろ");
        wordList.add("トルコ嬢");
        wordList.add("トルコ風呂");
        wordList.add("ニガー");
        wordList.add("ニグロ");
        wordList.add("にんぴにん");
        wordList.add("はんとうじん");
        wordList.add("マンコ");
        wordList.add("まんこ");
        wordList.add("レイプ");
        wordList.add("れいぷ");
        wordList.add("低能");
        wordList.add("屠殺");
        wordList.add("強姦");
        wordList.add("援交");
        wordList.add("支那人");
        wordList.add("精薄");
        wordList.add("精薄者");
        wordList.add("輪姦");
    }

    @Subscribe(order = PostOrder.FIRST)
    public void onPlayerChat(PlayerChatEvent event) {
        Player player = event.getPlayer();
        String message = event.getMessage();

        for (String word : wordList) {
            if (message.toLowerCase().contains(word.toLowerCase())) {
                message = message.replaceAll(word, "*".repeat(word.length()));
            }
        }

        broadcast(player, message);
    }

    private void broadcast(Player player, String message) {
        Optional<ServerConnection> serverConnection = player.getCurrentServer();
        RegisteredServer registeredServer = null;
        if (serverConnection.isPresent()) {
            registeredServer = serverConnection.get().getServer();
        }

        String sendMessage = serverConnection.map(connection -> "[" + Utils.getServerName(connection.getServerInfo().getName()) + "] <" + player.getUsername() + "> " + message)
                .orElseGet(() -> "[UNKNOWN] <" + player.getUsername() + "> " + message);

        TextComponent textComponent = Component.text(sendMessage);
        // send message to other server
        for (RegisteredServer server : this.proxyServer.getAllServers()) {
            if (!Objects.equals(server, registeredServer)) {
                server.sendMessage(textComponent);
            }
        }
    }

}
